# Generated by Django 5.0.7 on 2024-07-20 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_financiamiento_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.marca'),
        ),
    ]
