# Generated by Django 5.0.7 on 2024-08-09 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_empleado_apellido_empleado_direccion_empleado_dni_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default='Direccion', max_length=255),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(default='DNI', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(default='Puesto', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(default='+Telefono', max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
